export const INDUSTRIES = [
  'Aerospace & Defense',
  'Agricultural Inputs',
  'Airlines',
  'Asset Management',
  'Auto & Truck Dealerships',
  'Auto Manufacturers',
  'Auto Parts',
  'Banks—Diversified',
  'Banks—Regional',
  'Beverages—Brewers',
  'Beverages—Non-Alcoholic',
  'Beverages—Wineries & Distilleries',
  'Biotechnology',
  'Building Materials',
  'Building Products & Equipment',
  'Capital Markets',
  'Communication Equipment',
  'Computer Hardware',
  'Confectioners',
  'Conglomerates',
  'Consumer Electronics',
  'Credit Services',
  'Diagnostics & Research',
  'Drug Manufacturers—General',
  'Drug Manufacturers—Specialty & Generic',
  'Electronic Components',
  'Electronic Gaming & Multimedia',
  'Entertainment',
  'Farm & Heavy Construction Machinery',
  'Farm Products',
  'Financial Data & Stock Exchanges',
  'Food Distribution',
  'Gold',
  'Health Information Services',
  'Healthcare Plans',
  'Home Improvement Retail',
  'Household & Personal Products',
  'Industrial Distribution',
  'Information Technology Services',
  'Insurance Brokers',
  'Insurance—Diversified',
  'Insurance—Life',
  'Internet Content & Information',
  'Internet Retail',
  'Leisure',
  'Lodging',
  'Medical Devices',
  'Medical Distribution',
  'Medical Instruments & Supplies',
  'Mortgage Finance',
  'Oil & Gas E&P',
  'Oil & Gas Equipment & Services',
  'Oil & Gas Integrated',
  'Oil & Gas Midstream',
  'Oil & Gas Refining & Marketing',
  'Other Industrial Metals & Mining',
  'Packaged Foods',
  'Packaging & Containers',
  'Pharmaceutical Retailers',
  'Publishing',
  'REIT—Healthcare Facilities',
  'REIT—Office',
  'REIT—Residential',
  'REIT—Retail',
  'REIT—Specialty',
  'Railroads',
  'Rental & Leasing Services',
  'Restaurants',
  'Scientific & Technical Instruments',
  'Semiconductor Equipment & Materials',
  'Semiconductors',
  'Shell Companies',
  'Software—Application',
  'Software—Infrastructure',
  'Solar',
  'Specialty Business Services',
  'Specialty Chemicals',
  'Specialty Industrial Machinery',
  'Specialty Retail',
  'Steel',
  'Telecom Services',
  'Tobacco',
  'Tools & Accessories',
  'Utilities—Diversified',
  'Utilities—Independent Power Producers',
  'Utilities—Regulated Electric',
  'Utilities—Regulated Gas',
  'Waste Management',
]

export const FOSSIL_FUEL_INDUSTRIES = [
  'Oil & Gas E&P',
  'Oil & Gas Equipment & Services',
  'Oil & Gas Integrated',
  'Oil & Gas Midstream',
  'Oil & Gas Refining & Marketing',
  'Other Industrial Metals & Mining',
  'Utilities—Diversified',
  'Utilities—Independent Power Producers',
  'Utilities—Regulated Electric',
  'Utilities—Regulated Gas',
]

export const CONTENTFUL_LINK = 'https://app.contentful.com/spaces/gslvrj5c21wx/'

export const TOOLTIP_DEFINITIONS = {
  SECTOR:
    'A sector is comprised of many industries and is used to describe large components of the overall economy (eg, Energy).',
  INDUSTRY:
    'An industry is comprised of companies that are closely related in their business activities and is used to describe nuanced components of a larger sector (eg, Oil & Gas).',
  ESG: 'An Environmental, Social, and Governance (ESG) rating that aims to measure how sustainably a company is conducting business and managing ESG risk factors.',
  NET_ASSET_VAL:
    'The Net Asset Value treemap employs nested rectangles to display investment distribution by net asset values. The largest rectangle signifies the total fund value, containing smaller rectangles representing diverse investment categories. Their sizes reflect proportional values, and colors differentiate categories.',
  FINANCED_EMISSIONS:
    "The Financed Emissions treemap uses nested rectangles to display how investments contribute to greenhouse gas emissions. It visualizes the distribution of emissions linked to an investor's portfolio, with the size of rectangles reflecting proportional emissions. Colors differentiate sectors or investments, providing a quick view of associated environmental impacts.",
}

export const UNDERLINED_TITLE_STYLING = {
  PARAGRAPH:
    'header-2 md:header-1 break-words pb-12 pt-4 text-center leading-8',
  UNDERLINE: 'underline decoration-clementine decoration-8',
}
