export const sectorEnum = {
  FINANCIAL_SERVICES: 'Financial Services',
  INDUSTRIALS: 'Industrials',
  TECHNOLOGY: 'Technology',
  UTILITIES: 'Utilities',
  HEALTHCARE: 'Healthcare',
  CONSUMER_CYCLICAL: 'Consumer Discretionary',
  COMMUNICATION_SERVICES: 'Communication Services',
  ENERGY: 'Energy',
  CONSUMER_DEFENSIVE: 'Consumer Staples',
  REAL_ESTATE: 'Real Estate',
  BASIC_MATERIALS: 'Basic Materials',
}

export const envGradeEnum = {
  AAA: 'AAA',
  AA: 'AA',
  A: 'A',
  BBB: 'BBB',
  BB: 'BB',
  B: 'B',
  CCC: 'CCC',
}

export const requestStatusEnum = {
  PENDING: 'Pending',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
}

export const datasetEnum = {
  COMPANY: 'Company',
  INVESTMENT: 'Investment',
  FUEL: 'Fuel',
  EMISSION: 'Emission',
  ENERGY: 'Energy',
}

export const netAssetValEnum = {
  '0-5M': [0, 5e6],
  '5M-10M': [5e6, 10e6],
  '10M-15M': [10e6, 15e6],
  '15M-20M': [15e6, 20e6],
  '20M+': [20e6, Number.MAX_SAFE_INTEGER],
}

export const FuelEnum = {
  biodiesels: 'Biodiesels',
  biogases: 'Biogases',
  coal: 'Coal',
  oil: 'Oil',
  gas: 'Gas',
  otherBiomass: 'Other Biomass',
  sustainableBiomass: 'Sustainable Biomass',
  otherRenewable: 'Other Renewable',
  otherNonRenewable: 'Other Non-Renewable',
}

export const IndustryEnum = {
  AEROSPACE_DEFENSE: 'Aerospace & Defense',
  AGRICULTURAL_INPUTS: 'Agricultural Inputs',
  AIRLINES: 'Airlines',
  ASSET_MANAGEMENT: 'Asset Management',
  AUTO_TRUCK_DEALERSHIPS: 'Auto & Truck Dealerships',
  AUTO_MANUFACTURERS: 'Auto Manufacturers',
  AUTO_PARTS: 'Auto Parts',
  BANKS_DIVERSIFIED: 'Banks—Diversified',
  BANKS_REGIONAL: 'Banks—Regional',
  BEVERAGES_BREWERS: 'Beverages—Brewers',
  BEVERAGES_NON_ALCOHOLIC: 'Beverages—Non-Alcoholic',
  BEVERAGES_WINERIES_DISTILLERIES: 'Beverages—Wineries & Distilleries',
  BIOTECHNOLOGY: 'Biotechnology',
  BUILDING_MATERIALS: 'Building Materials',
  BUILDING_PRODUCTS_EQUIPMENT: 'Building Products & Equipment',
  CAPITAL_MARKETS: 'Capital Markets',
  COMMUNICATION_EQUIPMENT: 'Communication Equipment',
  COMPUTER_HARDWARE: 'Computer Hardware',
  CONFECTIONERS: 'Confectioners',
  CONGLOMERATES: 'Conglomerates',
  CONSUMER_ELECTRONICS: 'Consumer Electronics',
  CREDIT_SERVICES: 'Credit Services',
  DIAGNOSTICS_RESEARCH: 'Diagnostics & Research',
  DRUG_MANUFACTURERS_GENERAL: 'Drug Manufacturers—General',
  DRUG_MANUFACTURERS_SPECIALTY_GENERIC:
    'Drug Manufacturers—Specialty & Generic',
  ELECTRONIC_COMPONENTS: 'Electronic Components',
  ELECTRONIC_GAMING_MULTIMEDIA: 'Electronic Gaming & Multimedia',
  ENTERTAINMENT: 'Entertainment',
  FARM_HEAVY_CONSTRUCTION_MACHINERY: 'Farm & Heavy Construction Machinery',
  FARM_PRODUCTS: 'Farm Products',
  FINANCIAL_DATA_STOCK_EXCHANGES: 'Financial Data & Stock Exchanges',
  FOOD_DISTRIBUTION: 'Food Distribution',
  GOLD: 'Gold',
  HEALTH_INFORMATION_SERVICES: 'Health Information Services',
  HEALTHCARE_PLANS: 'Healthcare Plans',
  HOME_IMPROVEMENT_RETAIL: 'Home Improvement Retail',
  HOUSEHOLD_PERSONAL_PRODUCTS: 'Household & Personal Products',
  INDUSTRIAL_DISTRIBUTION: 'Industrial Distribution',
  INFORMATION_TECHNOLOGY_SERVICES: 'Information Technology Services',
  INSURANCE_BROKERS: 'Insurance Brokers',
  INSURANCE_DIVERSIFIED: 'Insurance—Diversified',
  INSURANCE_LIFE: 'Insurance—Life',
  INTERNET_CONTENT_INFORMATION: 'Internet Content & Information',
  INTERNET_RETAIL: 'Internet Retail',
  LEISURE: 'Leisure',
  LODGING: 'Lodging',
  MEDICAL_DEVICES: 'Medical Devices',
  MEDICAL_DISTRIBUTION: 'Medical Distribution',
  MEDICAL_INSTRUMENTS_SUPPLIES: 'Medical Instruments & Supplies',
  MORTGAGE_FINANCE: 'Mortgage Finance',
  OIL_GAS_EP: 'Oil & Gas E&P',
  OIL_GAS_EQUIPMENT_SERVICES: 'Oil & Gas Equipment & Services',
  OIL_GAS_INTEGRATED: 'Oil & Gas Integrated',
  OIL_GAS_MIDSTREAM: 'Oil & Gas Midstream',
  OIL_GAS_REFINING_MARKETING: 'Oil & Gas Refining & Marketing',
  OTHER_INDUSTRIAL_METALS_MINING: 'Other Industrial Metals & Mining',
  PACKAGED_FOODS: 'Packaged Foods',
  PACKAGING_CONTAINERS: 'Packaging & Containers',
  PHARMACEUTICAL_RETAILERS: 'Pharmaceutical Retailers',
  PUBLISHING: 'Publishing',
  REIT_HEALTHCARE_FACILITIES: 'REIT—Healthcare Facilities',
  REIT_OFFICE: 'REIT—Office',
  REIT_RESIDENTIAL: 'REIT—Residential',
  REIT_RETAIL: 'REIT—Retail',
  REIT_SPECIALTY: 'REIT—Specialty',
  RAILROADS: 'Railroads',
  RENTAL_LEASING_SERVICES: 'Rental & Leasing Services',
  RESTAURANTS: 'Restaurants',
  SCIENTIFIC_TECHNICAL_INSTRUMENTS: 'Scientific & Technical Instruments',
  SEMICONDUCTOR_EQUIPMENT_MATERIALS: 'Semiconductor Equipment & Materials',
  SEMICONDUCTORS: 'Semiconductors',
  SHELL_COMPANIES: 'Shell Companies',
  SOFTWARE_APPLICATION: 'Software—Application',
  SOFTWARE_INFRASTRUCTURE: 'Software—Infrastructure',
  SOLAR: 'Solar',
  SPECIALTY_BUSINESS_SERVICES: 'Specialty Business Services',
  SPECIALTY_CHEMICALS: 'Specialty Chemicals',
  SPECIALTY_INDUSTRIAL_MACHINERY: 'Specialty Industrial Machinery',
  SPECIALTY_RETAIL: 'Specialty Retail',
  STEEL: 'Steel',
  TELECOM_SERVICES: 'Telecom Services',
  TOBACCO: 'Tobacco',
  TOOLS_ACCESSORIES: 'Tools & Accessories',
  UTILITIES_DIVERSIFIED: 'Utilities—Diversified',
  UTILITIES_INDEPENDENT_POWER_PRODUCERS:
    'Utilities—Independent Power Producers',
  UTILITIES_REGULATED_ELECTRIC: 'Utilities—Regulated Electric',
  UTILITIES_REGULATED_GAS: 'Utilities—Regulated Gas',
  WASTE_MANAGEMENT: 'Waste Management',
}
